_target_: model.vae.VAE
latent_size: 100
encoder:
  _target_: model.encoder_decoder.vae_ROI_encoder
  input_size: ${num_features:${dataset.user}}
  output_size: ${model.latent_size}
decoder:
  _target_: model.encoder_decoder.vae_ROI_decoder
  input_size: ${model.latent_size}
  output_size: ${num_features:${dataset.user}}