_target_: model.vae.VAE
latent_size: 100
encoder:
  _target_: model.encoder_decoder.vae_roi_encoder
  input_features: ${num_features:${dataset.user}}
  output_features: ${intprod:${model.latent_features},2}
decoder:
  _target_: model.encoder_decoder.vae_roi_decoder
  input_features: ${model.latent_features}
  output_features: ${num_features:${dataset.user}}
opt:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
